### ISSUE TITLE
Matchup yelp IDs with TA IDs not in Crosswalk

### ISSUE THREAD

**Issue by jhugman** [mozilla-mobile/prox-server#25]
Because Factual Crosswalk isn't reliable.

This would be a regular crawl, disconnected with a user hitting the the prox-server API.

This would also include add new Crosswalk records to the Factual database.

**Comment by jhugman** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [As a user I want to get information from a variety of sources as often as possible.](https://trello.com/c/FhGNkUeQ/170-as-a-user-i-want-to-get-information-from-a-variety-of-sources-as-often-as-possible)

**Comment by jhugman** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Build replacement for Factual Crosswalk API](https://trello.com/c/y6dODMMJ/134-build-replacement-for-factual-crosswalk-api)

**Comment by mcomella** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Prox shows information from all existing sources - Yelp, TripAdvisor and Wikipedia](https://trello.com/c/QlakMpDt/363-prox-shows-information-from-all-existing-sources-yelp-tripadvisor-and-wikipedia)

**Comment by mcomella** [comment]
Steps:

1. Are we running out of Factual calls during the crawl and missing data because of that? (See also #88)
1. Figure out which Yelp places are missing TA data (re-use https://github.com/mozilla-mobile/prox-server/pull/86 ? Or maybe this is dependent on ^)
1. Create automation that matches Yelp -> TA (search by place name & gps in TA, do fuzzy name match to confirm). If it's correct often enough, use it, else...
1. Do ^, but have a human check over that the results are correct (and allow them to add in corrections).

As James mentions, it'd be great to give back our findings to Factual.

**Comment by mcomella** [comment]
I discovered we can put <place-name> and <coord> into TA's location_mapper API and it'll pass back IDs – no dealing with messy search!

In my first experiment, centered on the Ferry Building, 15/50 (30%) places were missing TA data:
* 8 are roughly uncorrectable (16% of the total)
  * 6 are not in TA
  * 2 have incorrect data in TA leading to mismatches ("Barbarossa" is named "Bubble Lounge" & TA thinks "Cafe Algiers" is closed)
* 2 may be a bug in my code (yay unicode) but the added accents are not in TA but are in Yelp so that could cause name mismatches (correctable if we remove accents before searching)
* 5 names are slightly different from Yelp to TA, causing a miss (e.g. "Mariposa Baking" on Yelp vs. "Mariposa" on TA).
  * To correct these, we could make a search by coordinates without place names (assuming the API works this way), take the results, and do our own name matching

The remaining 35 places were correct.

The full analysis is [in a gist](https://gist.github.com/mcomella/4a73c84a69dba97efff4105eb413c4d4).

Next TODO:
* ~Try to fix unicode bug~
* ~(?) Make this verification easily reproducible~
* ~Verify results in other locations are consistent (e.g. 30% missing)~
* If consistent, try to correct for name mismatches
* (Make code easily runnable, finding missing places from cache, getting our own crosswalk for these places, and updating the cache with these places)

**Comment by mcomella** [comment]
My current implementation puts the info directly into TA's location_mapper, taking the first result, and, if there are no results, strips any accents and tries again. A possible improvement is to remove the name query and do our own place matching.

With the current implementation, using the 50 best match Yelp results with our [top level categories](https://github.com/mozilla-mobile/prox-server/blob/6075e9f871207dad3b6b109402bd8434ff0bc43d/config.py#L16) from an 800m radius around the following locations, I got the following results:
* Ferry Building SF
  * 72% (36/50) correct matches
  * **5 name mismatches**
  * 6 places not on TA
  * 2 incorrect data in TA causing mismatch
  * 1 food truck (so matching location isn't really possible)
* YVR office
  * 82% (41/50) correct matches (1 place had different address between the two services)
  * **8 name mismatches**
  * 1 place not on TA
* Cloud Gate in Chicago
  * 78% (39/50) correct matches
  * **9 name mismatches**
  * 2 places not on TA

Notes:
* "Best match" will likely be more prominent locations so there's more likely to be TA matches (I figured these are the locations we'd want to surface anyway).
* Bolded name mismatches are potentially correctable (with the improvement mentioned above), but could introduce more error
* My raw notes (with specific name mismatches & sfo, yvr., chi place list) can be found [in this gist.](https://gist.github.com/mcomella/74bc9375a65433380e09204cd378deaf)
* I've been storing a list of name mismatches in `docs/yelp_at_name_mismatches.yml`

Updated TODO:
* We should compare our success rates against factual crosswalk (to have a metric of improvement).
  * If we haven't improved much, consider the improvement mentioned above ^
* ? Test on distance sort, rather than best match, for a more realistic test
* Find places missing TA data from place cache, store their crosswalk
* Figure out how to merge crosswalk ^ into main code base

**Comment by mcomella** [comment]
Update for non-dense area and analysis of Factual crosswalk:

Data: 0.5km crawl around Nashville (36.162963, -86.780758) = 41 places. Adjusting for places where Yelp serves an area rather than a specific location (6), there are 35 places.

* 74% (26/35) correct matches
  * **6 name mismatches**
  * 1 not on TA
  * 2 food trucks
  * Unioning the results of Factual crosswalk, we get to 31/35 (89%)
    * Removing the places that are uncorrectable, there is only one place missing ("Crazy Town Nashville") for 97% (31/32)
    * Factual gets 5 unique places, we get 15 unique
    * Factual alone gets 16 total places

Raw notes added [to the gist](https://gist.github.com/mcomella/74bc9375a65433380e09204cd378deaf).

---
Overall, it seems we're getting about 75% correct from this method. This one test of factual shows 46% correct for TA.

**Comment by mcomella** [comment]
We can do yelp -> TA: we just need to integrate (#91).
