### ISSUE TITLE
Create tooling to show if a Yelp place is in the DB

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/prox-server#90]
Suggestion: make it a website so non-engineers can access.

Question: if we expect to have all places, how necessary is this?

**Comment by mcomella** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Prox shows all places that I find on Yelp around me](https://trello.com/c/p2e8Ecwh/362-prox-shows-all-places-that-i-find-on-yelp-around-me)

**Comment by liuche** [comment]
As a (temporary) workaround (until this becomes higher priority), for whichever Firebase segment we're crawling in (hopefully not production, some dev/personal branch), we can substitute the yelp-id into this url - if it's null, the place doesn't exist, otherwise the details should pop up.

https://console.firebase.google.com/project/prox-server-cf63e/database/data/production/venues/details/<yelp-id-of-item>

**Comment by mcomella** [comment]
Closing as liuche found a solution ^.
